/**
 * Generated by tools/theory-distill.mjs after human review.
 * Do not put transcripts, PDFs, media paths, Whisper models, or long quotations here.
 */
export type BundledTheoryCard = {
  id: string;
  phase: "opening" | "middle" | "endgame";
  title: string;
  summary: string;
  appliesWhen: string;
  risk: string;
  courseName: string;
  lessonTitle: string;
  timecode?: string;
};

export const bundledTheoryKnowledge = {
  version: 1,
  generatedAt: "",
  cards: [] as BundledTheoryCard[],
};
