export type Piece = { row: number; col: number; color: "red" | "black"; kind: string; label: string };
export type MoveSquare = { row: number; col: number };
export type Side = "红方" | "黑方";
export type MoveItem = {
  id: string;
  iccs: string;
  notation: string;
  movedBy: Side;
  from: MoveSquare;
  to: MoveSquare;
  scoreCp?: number;
  mate?: number;
  comment: string;
  isMainline: boolean;
};
export type ManualTreeNode = {
  move: MoveItem;
  children: ManualTreeNode[];
};
export type BoardState = {
  fen: string;
  rootSideToMove: Side;
  rootScoreCp?: number;
  rootMate?: number;
  sideToMove: Side;
  status: string;
  ruleName?: string;
  ruleVerdict?: string;
  ruleReason?: string;
  pieces: Piece[];
  history: MoveItem[];
  continuation: MoveItem[];
  branches: MoveItem[];
  siblingBranches?: MoveItem[];
  manualTree?: ManualTreeNode[];
  currentNode?: string;
  title: string;
  note: string;
  sourcePath?: string;
  sourceFormat?: string;
  playable: boolean;
  xqbCandidates?: XqbCandidate[];
};
export type XqbCandidate = {
  iccs: string;
  notation: string;
  score: number;
  win: number;
  draw: number;
  loss: number;
  winRate?: number;
  memo?: string;
  source: string;
};
export type CloudBookCandidate = {
  iccs: string;
  notation: string;
  score: number;
  rank?: number;
  winRate?: number;
  memo?: string;
  source: string;
  cached: boolean;
};
export type AnalysisLine = {
  depth?: number;
  scoreCp?: number;
  mate?: number;
  nps?: number;
  timeMs?: number;
  hashfull?: number;
  multipv: number;
  notation?: string[];
  pv: string[];
};
export type PreviewLineStep = {
  fen: string;
  notation: string;
  movedBy: Side;
  from: MoveSquare;
  to: MoveSquare;
  pieces: Piece[];
  status: string;
};
export type AnalysisOptions = {
  enginePath: string;
  engineId?: string;
  engineName?: string;
  analysisSessionId?: number;
  fen: string;
  searchMode: "time" | "depth" | "nodes" | "infinite";
  searchValue: number;
  threads: number;
  hashMb: number;
  multipv: number;
  serverUrl: string;
  token: string;
  searchMoves?: string[];
  excludeMove?: string;
};
export type ReportPhase = "opening" | "middle" | "endgame";
export type QualityGrade = "优" | "良" | "中" | "差" | "错";
export type GameReportMoveDto = { nodeId: string; iccs?: string; notation: string; movedBy: Side };
export type OpeningBookHitDto = { code: string; name: string; ply: number; source: string };
export type GameReportPositionDto = {
  fen: string;
  sideToMove: Side;
  ply: number;
  phase: ReportPhase;
  material?: number;
  scoreCp?: number;
  mate?: number;
  depth?: number;
  elapsedMs?: number;
  cached?: boolean;
  bestIccs?: string;
  bestNotation?: string;
  pvNotation?: string[];
  opening?: OpeningBookHitDto;
  move?: GameReportMoveDto;
};
export type GameReportDatasetDto = {
  gameId: string;
  lineSignature: string;
  engineFingerprint: string;
  configHash: string;
  generatedAt: string;
  stale: boolean;
  analysisDepth?: number;
  cachedPositions?: number;
  positions: GameReportPositionDto[];
};
export type GameReportOptionsDto = {
  enginePath: string;
  reportDepth: number;
  xqbBookPaths?: string[];
  threads: number;
  hashMb: number;
};
export type GameReportProgressDto = {
  completed: number;
  total: number;
  nodeId?: string;
  elapsedMs: number;
  targetDepth?: number;
  currentDepth?: number;
  cached?: number;
  estimatedRemainingMs?: number;
  state: "running" | "cancelled" | "complete";
};
export type ReportQualityCountsDto = {
  excellent: number;
  good: number;
  average: number;
  poor: number;
  error: number;
  missedMate: number;
};
export type ReportSidePresentationDto = {
  side: Side;
  overall?: number;
  grade?: QualityGrade;
  phases: Record<ReportPhase, number | undefined>;
  phaseGrades: Record<ReportPhase, QualityGrade | undefined>;
  counts: ReportQualityCountsDto;
  coachQuality: QualityGrade | "样本不足";
  coachSummary: string;
  dimensions: Record<"opening" | "middle" | "endgame" | "accuracy" | "stability", number | undefined>;
};
export type MoveCoachInsightDto = {
  intent: string;
  weakness: string;
  solution: string;
  branchPlan: string;
};
export type BranchCoachInsightDto = {
  branchName: string;
  branchPurpose: string;
  namingTips: string[];
  weaknessFixes: string[];
  studyPlan: string[];
};
export type ReportIssuePresentationDto = {
  nodeId: string;
  notation: string;
  movedBy: Side;
  lossCp: number;
  score: number;
  grade: QualityGrade;
  missedMate: boolean;
  redScoreCp: number;
  deltaCp: number;
  opening?: OpeningBookHitDto;
  bestIccs?: string;
  bestNotation?: string;
  pvNotation?: string[];
  coach: MoveCoachInsightDto;
};
export type GameReportPresentationDto = {
  title: string;
  generatedAt: string;
  stale: boolean;
  analysisDepth?: number;
  engineLabel: string;
  totalElapsedMs: number;
  cachedPositions: number;
  openingSummary?: { code: string; name: string; officialMoves: number; source: string };
  red: ReportSidePresentationDto;
  black: ReportSidePresentationDto;
  coachInsights: BranchCoachInsightDto;
  trend: Array<{ label: string; scoreCp: number; nodeId?: string; deltaCp?: number }>;
  issues: ReportIssuePresentationDto[];
  standards: Array<{ grade: QualityGrade; qualityRange: string; description: string }>;
  scoreGuide: Array<{ scoreCp: number; label: string }>;
  disclaimer: string;
};
export type SyncResult = { uploaded: number; downloaded: number; cursor: number };
export const BUILTIN_ENGINE_PATH = "builtin:pikafish";
export const BUILTIN_FAIRY_ENGINE_PATH = "builtin:fairy-stockfish";
export type WorkspaceLayoutMode = "studio" | "compact";
export type ManualViewMode = "track" | "tree";
export type RuleMode = "domestic2020" | "asianAxf";
export type SkinFolder = "default" | "hongmu" | "jingdian" | "xinghe";
export type LegacySkinId = "original" | "classic" | "neon" | "jade" | "imperial";
export type SkinId = SkinFolder | LegacySkinId;
export type DesktopPreferencesDto = {
  enginePath: string;
  threads: number;
  hashMb: number;
  multipv: number;
  candidateLineMoves: number;
  searchMode: "time" | "depth" | "nodes" | "infinite";
  searchValue: number;
  moveTimeMs: number;
  ponder: boolean;
  autoAnalyze: boolean;
  libraryCollapsed: boolean;
  candidateRailCollapsed: boolean;
  analysisPanelCollapsed: boolean;
  evaluationCollapsed: boolean;
  branchArrowColor: string;
  workspacePanel: "moves" | "analysis" | "trend" | "summary" | "report" | "theory";
  layoutMode: WorkspaceLayoutMode;
  manualViewMode: ManualViewMode;
  colorTheme: "light" | "dark";
  boardSkin: SkinId;
  pieceSkin: SkinId;
  reportDepth: number;
  xqbBookPaths?: string[];
  disabledXqbBookPaths?: string[];
  activeEngineId?: string;
  analysisEngineMode: "single" | "parallel";
  parallelEngineIds: string[];
  parallelEnginePaths?: string[];
  cloudBookEnabled?: boolean;
  cloudBookUrl?: string;
  ruleMode: RuleMode;
  linkCaptureSource?: CaptureSource;
  linkRecognitionMode?: RecognitionMode;
  linkMode?: LinkMode;
  linkStableFrames?: number;
  linkConfidenceThreshold?: number;
  linkAnimationConfirmation?: boolean;
  serverUrl: string;
};
export type SyncAccountDto = {
  serverUrl: string;
  userId?: string;
  email?: string;
  status: "unbound" | "signedOut" | "signedIn" | "expired";
  lastSyncResult?: string;
};
export type SubscriptionDto = {
  plan: "free" | "pro";
  status: "inactive" | "active";
  source: string;
  startsAt: string;
  expiresAt: string;
  cloudAnalysisQuota: number;
  cloudAnalysisUsed: number;
};
export type TrainingTaskDto = {
  id: string;
  gameId: string;
  nodeId: string;
  title: string;
  detail: string;
  completedAt?: string;
  createdAt: string;
};
export type StudySessionDto = {
  id: string;
  gameId: string;
  nodeId?: string;
  reflection: string;
  tags: string[];
  createdAt: string;
};
export type TheoryPhase = "opening" | "middle" | "endgame";
export type TheoryLessonDto = {
  id: number;
  phase: TheoryPhase;
  courseName: string;
  title: string;
  sourcePath: string;
  fingerprint: string;
  transcriptionStatus: "queued" | "processing" | "complete" | "failed";
  durationMs?: number;
  scannedAt: string;
};
export type TheoryCardDto = {
  id: number;
  lessonId: number;
  phase: TheoryPhase;
  title: string;
  summary: string;
  appliesWhen: string;
  risk: string;
  timecode?: string;
  reviewStatus: "pending" | "approved" | "rejected";
  courseName: string;
  lessonTitle: string;
};
export type TheoryLibraryDto = { lessons: TheoryLessonDto[]; cards: TheoryCardDto[]; downloadingFiles: number };
export type EngineProbeDto = {
  path: string;
  protocol: "uci" | "ucci";
  engineVersion?: string;
  engineSha256?: string;
  nnueFile?: string;
  nnueVersion?: string;
  nnueSha256?: string;
  fingerprint?: string;
};
export type EngineProfileDto = { id: string; name: string; executablePath: string; protocol: "uci" | "ucci"; active: boolean };
export type EngineArenaPlayerDto = { name: string; enginePath: string };
export type EngineArenaOptionsDto = {
  playerA: EngineArenaPlayerDto;
  playerB: EngineArenaPlayerDto;
  games: number;
  moveTimeMs: number;
  threads: number;
  hashMb: number;
  maxPlies: number;
};
export type EngineArenaGameDto = {
  index: number;
  red: string;
  black: string;
  result: string;
  winner?: string;
  reason: string;
  plies: number;
  moves: string[];
};
export type EngineArenaScoreDto = { name: string; wins: number; draws: number; losses: number; points: number };
export type EngineArenaResultDto = {
  playerA: EngineArenaScoreDto;
  playerB: EngineArenaScoreDto;
  games: EngineArenaGameDto[];
  moveTimeMs: number;
  maxPlies: number;
  ruleName: string;
  summary: string;
};
export type GameSummary = { id: string; title: string; fen: string; updatedAt: string; current: boolean };
export type EnginePlayOptions = { enginePath: string; moveTimeMs: number; threads: number; hashMb: number; ponder: boolean };
export type EngineMoveResult = { board: BoardState; ponder?: string };
export type EngineRuntimeState = "idle" | "analyzing" | "thinking" | "pondering" | "stopping" | "faulted";
export type CaptureSource = "windowLink" | "desktopDetect" | "imageImport" | "cameraBoard";
export type RecognitionMode = "yoloBoard" | "perspectiveGrid";
export type LinkMode = "spectate" | "confirmPlay" | "autoPlay";
export type LinkSessionState = "stopped" | "detectingCorners" | "rectifyingBoard" | "classifyingSquares" | "calibrating" | "needsManualCorrection" | "waitingStableFrames" | "tracking" | "paused";
export type LinkAutoSide = "red" | "black";
export type StartLinkSessionRequest = { source: CaptureSource; recognitionMode: RecognitionMode; mode: LinkMode; stableFrames: number; autoSide?: LinkAutoSide };
export type LinkObservation = { state: LinkSessionState; accepted: boolean; moveIccs?: string; reason?: string; board?: BoardState; capturePreviewAvailable?: boolean };
export type LinkSessionStatus = { source: CaptureSource; mode: LinkMode; state: LinkSessionState; reason?: string; frameRate: number; confidence?: number; stableFrames: number; requiredStableFrames: number; latestFen?: string; lastMove?: string; autoSide?: LinkAutoSide; captureRunning: boolean };
export type ExportFormat = "pgn" | "chinese" | "dhtmlxq";
export type ReplayExportScope = "currentSelection" | "mainline";
export type EngineRuntimeEvent =
  | { type: "state"; state: EngineRuntimeState }
  | { type: "info"; fen: string; line: AnalysisLine }
  | { type: "analysisInfo"; engineId?: string; engineName?: string; analysisSessionId?: number; fen: string; line: AnalysisLine }
  | { type: "bestmove"; fen: string; best: string; ponder?: string }
  | { type: "error"; message: string };

export interface ChessPlatform {
  readonly kind: "desktop" | "web";
  initialize(): Promise<Partial<BoardState>>;
  listGames(): Promise<GameSummary[]>;
  openGame(gameId: string): Promise<Partial<BoardState>>;
  detectEngine(): Promise<string | null>;
  getDesktopPreferences(): Promise<DesktopPreferencesDto>;
  saveDesktopPreferences(preferences: DesktopPreferencesDto): Promise<DesktopPreferencesDto>;
  chooseEngineExecutable(currentPath?: string): Promise<string | undefined>;
  probeEngine(path: string): Promise<EngineProbeDto>;
  listEngineProfiles(): Promise<EngineProfileDto[]>;
  registerEngineProfile(name: string, path: string): Promise<EngineProfileDto>;
  setActiveEngineProfile(id: string): Promise<DesktopPreferencesDto>;
  deleteEngineProfile(id: string): Promise<DesktopPreferencesDto>;
  queryCloudOpeningBook(fen: string): Promise<CloudBookCandidate[]>;
  listCoachReports(): Promise<GameReportDatasetDto[]>;
  listTrainingTasks(): Promise<TrainingTaskDto[]>;
  generateTrainingTasks(): Promise<TrainingTaskDto[]>;
  listStudySessions(): Promise<StudySessionDto[]>;
  saveStudySession(reflection: string, tags: string[]): Promise<StudySessionDto>;
  scanTheoryLibrary(): Promise<TheoryLibraryDto>;
  getTheoryLibrary(): Promise<TheoryLibraryDto>;
  reviewTheoryCard(card: TheoryCardDto): Promise<TheoryCardDto>;
  createTheoryCard(card: Pick<TheoryCardDto, "lessonId" | "title" | "summary" | "appliesWhen" | "risk" | "timecode">): Promise<TheoryCardDto>;
  completeTrainingTask(taskId: string, completed: boolean): Promise<void>;
  playMove(iccs: string): Promise<Partial<BoardState>>;
  prepareLinkSelectionWindow(): Promise<void>;
  startLinkSession(request: StartLinkSessionRequest): Promise<LinkObservation>;
  stopLinkSession(): Promise<LinkObservation>;
  getLinkSessionStatus(): Promise<LinkSessionStatus>;
  pauseLinkSession(): Promise<LinkSessionStatus>;
  recalibrateLinkSession(): Promise<LinkSessionStatus>;
  getLinkCapturePreview(): Promise<string | undefined>;
  submitLinkPosition(fen: string): Promise<LinkObservation>;
  confirmLinkEngineMove(iccs: string): Promise<boolean>;
  importRecognizedPosition(fen: string, title?: string): Promise<Partial<BoardState>>;
  newGame(fen: string, title?: string, note?: string): Promise<Partial<BoardState>>;
  openDocument(): Promise<Partial<BoardState> | undefined>;
  importXqbOpeningBook(): Promise<Partial<BoardState> | undefined>;
  saveDocument(saveAs?: boolean): Promise<string | undefined>;
  copyPosition(fen: string): Promise<void>;
  copyGame(mainlineOnly?: boolean): Promise<void>;
  copyExport(format: ExportFormat): Promise<void>;
  exportManualFile(format: ExportFormat, title: string): Promise<string | undefined>;
  exportManualPdf(title: string): Promise<string | undefined>;
  exportReplayGif(title: string, scope: ReplayExportScope): Promise<string | undefined>;
  exportMindMapSvg(title: string, svg: string): Promise<string | undefined>;
  exportTextFile(title: string, contents: string): Promise<string | undefined>;
  pasteDocument(): Promise<Partial<BoardState>>;
  updateGameMetadata(title: string, note: string): Promise<Partial<BoardState>>;
  reorderBranches(nodeIds: string[]): Promise<Partial<BoardState>>;
  navigateTo(nodeId?: string): Promise<Partial<BoardState>>;
  updateComment(nodeId: string, comment: string): Promise<Partial<BoardState>>;
  setMainline(nodeId: string): Promise<Partial<BoardState>>;
  deleteNode(nodeId: string): Promise<Partial<BoardState>>;
  previewLine(fen: string, pv: string[]): Promise<PreviewLineStep[]>;
  analyze(options: AnalysisOptions): Promise<AnalysisLine[]>;
  runEngineArena(options: EngineArenaOptionsDto): Promise<EngineArenaResultDto>;
  playEngineMove(options: EnginePlayOptions): Promise<EngineMoveResult>;
  moveNow(): Promise<boolean>;
  stopEnginePlay(): Promise<boolean>;
  stopAnalysis(discardResult?: boolean): Promise<boolean>;
  subscribeEngineEvents(listener: (event: EngineRuntimeEvent) => void): Promise<() => void>;
  generateGameReport(options: GameReportOptionsDto): Promise<GameReportDatasetDto>;
  cancelGameReport(): Promise<boolean>;
  getGameReport(): Promise<GameReportDatasetDto | undefined>;
  exportGameReportPdf(report: GameReportPresentationDto): Promise<string | undefined>;
  subscribeGameReportProgress(listener: (progress: GameReportProgressDto) => void): Promise<() => void>;
  loadSavedAnalysis(fen: string): Promise<AnalysisLine[]>;
  openCompactFloatingPanel(panel: "engine" | "manual" | "cloud" | "link"): Promise<boolean>;
  returnCompactFloatingPanel(panel: "engine" | "manual" | "cloud" | "link"): Promise<boolean>;
  getSyncAccount(): Promise<SyncAccountDto>;
  getSubscription(): Promise<SubscriptionDto>;
  redeemSubscriptionCode(code: string): Promise<SubscriptionDto>;
  registerSyncAccount(email: string, password: string): Promise<SyncAccountDto>;
  loginSyncAccount(email: string, password: string): Promise<SyncAccountDto>;
  logoutSyncAccount(): Promise<SyncAccountDto>;
  unbindSyncAccount(): Promise<SyncAccountDto>;
  synchronize(serverUrl?: string, token?: string): Promise<SyncResult>;
}
